// <auto-generated />
using ArchitectureAspNetCoreEFMySQL.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArchitectureAspNetCoreEFMySQL.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArchitectureAspNetCoreEFMySQL.Core.Domain.Entities.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnoFabricacao")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("AnoModelo")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
